"""Add author_id to Comment model and enforce not-null constraints

Revision ID: 2f003d8010a6
Revises: 9f1d6835c014
Create Date: 2025-08-01 09:44:46.075355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '2f003d8010a6'
down_revision = '9f1d6835c014'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###