"""Remove author_name from comments

Revision ID: 80512f8ce5d4
Revises: 2f003d8010a6
Create Date: 2025-08-01 10:07:01.829774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '80512f8ce5d4'
down_revision = '2f003d8010a6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###