"""add is_admin to users

Revision ID: 8fb21161ee2b
Revises: bdc77dd969bd
Create Date: 2025-07-29 11:09:18.490943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '8fb21161ee2b'
down_revision = 'bdc77dd969bd'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###