"""Add bio field to users table

Revision ID: bdc77dd969bd
Revises: e35bc7b76dba
Create Date: 2025-07-29 01:11:13.383817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = 'bdc77dd969bd'
down_revision = 'e35bc7b76dba'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###